
class MACD:

    UPPER = "MACD_UPPER"
    MIDDLE = "MACD_MIDDLE"
    LOWER = "MACD_LOWER"

    SIGNAL = "SIGNAL"
    UP_HIST = "UP_HISTOGRAM"
    MID_HIST = "MID_HISTOGRAM"
    LOW_HIST = "LOW_HISTOGRAM"