
class MACD:

    UPPER = "MACD_UPPER"
    MIDDLE = "MACD_MIDDLE"
    LOWER = "MACD_LOWER"

    SIGNAL = "SIGNAL"
    UP_SIGNAL = "UP_SIGNAL"
    MID_SIGNAL = "MID_SIGNAL"
    LOW_SIGNAL = "LOW_SIGNAL"

    UP_INCREASE = "MACD_UPPER_INCREASE"
    MID_INCREASE = "MACD_MIDDLE_INCREASE"
    LOW_INCREASE = "MACD_LOWER_INCREASE"