
class MACD:
    UPPER = "MACD_UPPER"
    MIDDLE = "MACD_MIDDLE"
    LOWER = "MACD_LOWER"

    UP_INCREASE = "MACD_UPPER_INCREASE"
    MID_INCREASE = "MACD_MIDDLE_INCREASE"
    LOW_INCREASE = "MACD_LOWER_INCREASE"