# -*- coding: utf-8 -*-
class EMA:
    SHORT = "EMA_SHORT"
    MID = "EMA_MID"
    LONG = "EMA_LONG"

class RSI:
    SHORT = "RSI_SHORT"
    SHORT_SIG = "RSI_SHORT_SIGNAL"
    SHORT_BULLISH = "RSI_SHORT_BULLISH"
    SHORT_BEARISH = "RSI_SHORT_BEARISH"

    LONG = "RSI_LONG"
    LONG_SIG = "RSI_LONG_SIGNAL"
    LONG_BULLISH = "RSI_LONG_BULLISH"
    LONG_BEARISH = "RSI_LONG_BEARISH"

    OVER_BOUGHT = 70
    OVER_SOLD = 30

class MACD:
    SHORT = "MACD_SHORT"
    SHORT_SIG = "MACD_SHORT_SIGNAL"
    SHORT_HIST = "MACD_SHORT_HIST"
    SHORT_BULLISH = "MACD_SHORT_BULLISH"
    SHORT_BEARISH = "MACD_SHORT_BEARISH"

    LONG = "MACD_LONG"
    LONG_SIG = "MACD_LONG_SIGNAL"
    LONG_HIST = "MACD_LONG_HIST"
    LONG_BULLISH = "MACD_LONG_BULLISH"
    LONG_BEARISH = "MACD_LONG_BEARISH"

class STOCHASTIC:
    D_FAST = "STOCHASTIC_D_FAST"
    K_SLOW = "STOCHASTIC_D_FAST"
    D_SLOW = "STOCHASTIC_D_SLOW"

    BULLISH = "STOCHASTIC_BULLISH"
    BEARISH = "STOCHASTIC_BEARISH"

    OVER_BOUGHT = 70
    OVER_SOLD = 30

class Stage:
    STABLE_INCREASE = 1
    END_OF_INCREASE = 2
    START_OF_DECREASE = 3
    STABLE_DECREASE = 4
    END_OF_DECREASE = 5
    START_OF_INCREASE = 6

class TimeFrame:
    MINUTE = "1m"
    MINUTE_3 = "3m"
    MINUTE_5 = "5m"
    MINUTE_10 = "10m"
    MINUTE_15 = "15m"
    HALF_HOUR = "30m"
    HOUR = "1h"
    HOUR_4 = "4h"

    KEYS = {
        MINUTE: 1,
        MINUTE_3: 3,
        MINUTE_5: 5,
        MINUTE_10: 10,
        MINUTE_15: 15,
        HALF_HOUR: 30,
        HOUR: 60,
        HOUR_4: 240,
    }