services:
  server-container:
    container_name: autotrading-green
    environment:
      TZ: "Asia/Seoul"
    image: upbit_trading:v1
    ports:
      - "8000:8000"
    build: .
    healthcheck:
      test: >
        bash -c ': > /dev/tcp/localhost/8000' || exit 1
      interval: 60s
      timeout: 10s
      retries: 2
    volumes:
      - ./log:/app/log
#  nginx:
#    image: upbit_nginx:v1
#    ports:
#      - "80:80"
#    build: ./nginx/