services:
  server-container:
    container_name: autotrading-blue
    image: upbit_trading:v1
    ports:
      - "8001:8000"
    build: .
    healthcheck:
      test: curl -f http://localhost:8001/health || exit 1
      interval: 60s
      timeout: 10s
      retries: 2
    volumes:
      - ./log:/app/log