services:
  server-container:
    container_name: autotrading-blue
    environment:
      TZ: "Asia/Seoul"
    image: autotrading:v1
    command: ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    expose:
      - "8000"
    build: .
    healthcheck:
      test: >
        bash -c ': > /dev/tcp/localhost/8000' || exit 1
      interval: 30s
      timeout: 10s
      retries: 2
    volumes:
      - ./log:/app/log
#  nginx:
#    image: upbit_nginx:v1
#    ports:
#      - "80:80"
#    build: ./nginx/