services:
  upbit-green:
    container_name: upbit-green
    image: upbit
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      TZ: "Asia/Seoul"
    ports:
      - "8001:8000"
    expose:
      - "8001"
    command: ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8001"]