name: dev-workflow

on:
  push:
    branches:
      - develop
jobs:
  SSH:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: ssh to compute engine
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          script: |
            cd AutoTrading
            git pull https://github.com/consoleolog/AutoTrading.git
  create-pr:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{secrets.GH_TOKEN}}
          commit-message: Create Pull Request with Github Actions
          base: main
          branch: ${{github.ref}}
          assignees: kec0130
          title: AutoTrading Update
          body: 'Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action'
